# Site settings
title: ZQY Blog
SEOTitle: 周琪岳的博客 | ZQY Blog
header-img: img/home-bg.jpg
email: zhou3655463@163.com
description: "ZQYAKIOI && WHILE(1) RP++"
keyword: "周琪岳,zqy,ZQY,zhouqiyue,C++,c++,酷町堂"
url: "https://www.luogu.com.cn/user/446233"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     huxpro
zhihu_username:     huxpro
github_username:    huxpro
twitter_username:   huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: hux

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "周琪岳,2019届KDT入坑OI选手,第37届合肥市信息学竞赛一等奖"
sidebar-avatar: ![Alt text](https://image.baidu.com/search/detail?ct=503316480&z=0&ipn=d&word=%E5%9C%B0%E7%90%83&hs=2&pn=0&spn=0&di=6380&pi=0&rn=1&tn=baiduimagedetail&is=0%2C0&ie=utf-8&oe=utf-8&cl=2&lm=-1&cs=4113676382%2C688541661&os=626485750%2C2874965687&simid=2545311548%2C2175359802&adpicid=0&lpn=0&ln=30&fr=ala&fm=&sme=&cg=&bdtype=0&oriquery=%E5%9C%B0%E7%90%83&objurl=https%3A%2F%2Fgimg2.baidu.com%2Fimage_search%2Fsrc%3Dhttp%3A%2F%2Fpic.baike.soso.com%2Fp%2F20120302%2F20120302143857-1178248017.jpg%26refer%3Dhttp%3A%2F%2Fpic.baike.soso.com%26app%3D2002%26size%3Df9999%2C10000%26q%3Da80%26n%3D0%26g%3D0n%26fmt%3Djpeg%3Fsec%3D1623935786%26t%3Dcf25a0b3b2c3f85e11e2ca4f00fc176c&fromurl=ippr_z2C%24qAzdH3FAzdH3Fkwthj_z%26e3Bf5f5_z%26e3Bv54AzdH3Fi890mn_z%26e3Bip4%3Ffr%3DSr6je%26fr%3Dscb09cnn0&gsm=1&islist=&querylist=)      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
        title: "周琪岳的KDT主页",
        href: "https://ke.codingtang.com/#/user/studentCenter?id=2296"
    }
]
